stages:
  - build
  - deploy

build:
  script:
    - docker build -t <docker-repo-url>/gin-api:$CI_COMMIT_SHA .
    - docker push <docker-repo-url>/gin-api:$CI_COMMIT_SHA

deploy:
  script:
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
    - kubectl apply -f k8s/ingress.yaml
